spring.datasource.url=jdbc:postgresql://localhost:5434/budgetapp
spring.datasource.username=postgres
spring.datasource.password=PUT_YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=org.postgresql.Driver